# Generated by Django 4.1.1 on 2022-09-28 02:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBlog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=400)),
                ('image', models.ImageField(upload_to='blog/images/')),
                ('date', models.DateField(verbose_name=datetime.date.today)),
            ],
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
